### ISSUE TITLE
Logger, onValueChanged and comment issue

### ISSUE THREAD

**Issue by Jamalianpour** [youngchan1988/json_editor#5]
Hello, at the first I should say thanks for your awesome repo
Anyway I have some issue with that

1. Why did you use logger package for validating data this is very annoying. Please add an options to disable that

![image](https://user-images.githubusercontent.com/29815018/160881979-853d5bf3-7b2a-45ea-ba48-765a191969d2.png)

2. There is some delay to update value in `onValueChanged`
for example I write this json and after that immediately press a button:
![image](https://user-images.githubusercontent.com/29815018/160883016-44bbafaf-3e89-4a3b-8566-04343099b7d3.png)
but I get this json as `JsonElement`:
```json
{
    "test": ""
}
``` 

3. When I try to add `jsonString` with a comment the comment does not display:
```dart
JsonEditor.string(
  jsonString: '''
  {
      // Insert your data here
  }
  ''',
  enabled: true,
  onValueChanged: (value) {
    document = value;
  },
),
```

**Comment by youngchan1988** [comment]
Hi there! Thanks a lot for your suggestion. I have optimized the code in 0.0.6.  About 2, `onValueChanged` called behind the analysis. So there is a delay to make sure the result is correct. You can have a try again. 😊
